services:
  postgres:
    image: postgres:15
    container_name: costs-db
    hostname: costs-db
    environment:
      POSTGRES_USER: marvin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: costs
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
